package bazel.v1

import bazel.Converter
import bazel.bazel.BazelContent
import bazel.bazel.BazelEvent
import bazel.events.*
import java.util.logging.Level
import java.util.logging.Logger

class BuildEventConverter(private val _bazelEventConverter: Converter<com.google.protobuf.Any, BazelContent>)
    : Converter<com.google.devtools.build.v1.OrderedBuildEvent, OrderedBuildEvent> {
    override fun convert(source: com.google.devtools.build.v1.OrderedBuildEvent): OrderedBuildEvent {
        val streamId = if (source.hasStreamId()) convert(source.streamId) else StreamId.default
        if (source.hasEvent()) {
            val event = source.event
            val sequenceNumber = source.sequenceNumber
            val eventTime = Timestamp(event.eventTime.seconds, event.eventTime.nanos)

            // An invocation attempt has started.
            // invocation_attempt_started = 51
            if (event.hasInvocationAttemptStarted()) {
                return InvocationAttemptStarted(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        event.invocationAttemptStarted.attemptNumber)
            }

            // An invocation attempt has finished.
            // invocation_attempt_finished = 52
            if (event.hasInvocationAttemptFinished()) {
                return InvocationAttemptFinished(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        if (event.invocationAttemptFinished.hasInvocationStatus()) convert(event.invocationAttemptFinished.invocationStatus) else Result.default,
                        if (event.invocationAttemptFinished.hasExitCode()) event.invocationAttemptFinished.exitCode.value else 0)
            }

            // The build is enqueued (just inserted to the build queue or put back
            // into the build queue due to a previous build failure).
            // build_enqueued = 53
            if (event.hasBuildEnqueued()) {
                return BuildEnqueued(
                        streamId,
                        sequenceNumber,
                        eventTime)
            }

            // The build has finished. Set when the build is terminated.
            // build_finished = 55
            if (event.hasBuildFinished()) {
                return BuildFinished(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        if (event.buildFinished.hasStatus()) convert(event.buildFinished.status) else Result.default)
            }

            // An event containing printed text.
            // console_output = 56
            if (event.hasConsoleOutput()) {
                return ConsoleOutput(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        convert(event.consoleOutput.type),
                        event.consoleOutput.textOutput)
            }

            // Indicates the end of a build event stream (with the same StreamId) from
            // a build component executing the requested build task.
            // *** This field does not indicate the WatchBuild RPC is finished. ***
            // component_stream_finished = 59
            if (event.hasComponentStreamFinished()) {
                return ComponentStreamFinished(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        convert(event.componentStreamFinished.type))
            }

            // Structured build event generated by Bazel about its execution progress.
            // bazel_event = 60
            if (event.hasBazelEvent()) {
                val bazelEvent = event.bazelEvent
                val content = _bazelEventConverter.convert(bazelEvent)
                return BazelEvent(
                        streamId,
                        sequenceNumber,
                        eventTime,
                        content)
            }

            // An event that contains supplemental tool-specific information about
            // build execution.
            // build_execution_event = 61

            // An event that contains supplemental tool-specific information about
            // source fetching.
            // source_fetch_event = 62

            logger.log(Level.SEVERE, "Unknown event type: $event")
        }

        return UnknownEvent(streamId)
    }

    private fun convert(finishType: com.google.devtools.build.v1.BuildEvent.BuildComponentStreamFinished.FinishType) =
            when(finishType.number) {
                1 -> FinishType.Finished
                2 -> FinishType.Expired
                else -> FinishType.Unspecified
            }

    private fun convert(consoleOutputStream: com.google.devtools.build.v1.ConsoleOutputStream) =
        when(consoleOutputStream.number) {
            1 -> ConsoleOutputStream.Stdout
            2 -> ConsoleOutputStream.Stderr
            else -> ConsoleOutputStream.Unknown
        }

    private fun convert(buildStatus: com.google.devtools.build.v1.BuildStatus) =
        Result(
                when (buildStatus.resultValue) {
                    1 -> BuildStatus.CommandSucceeded
                    2 -> BuildStatus.CommandFailed
                    3 -> BuildStatus.UserError
                    4 -> BuildStatus.SystemError
                    5 -> BuildStatus.ResourceExhausted
                    6 -> BuildStatus.InvocationDeadlineExceeded
                    8 -> BuildStatus.RequestDeadlineExceeded
                    7 -> BuildStatus.Cancelled
                    else -> BuildStatus.Unknown
                }
        )

    private fun convert(originalStreamId: com.google.devtools.build.v1.StreamId) =
            StreamId(
                    originalStreamId.buildId,
                    originalStreamId.invocationId,
                    convert(originalStreamId.component))

    private fun convert(originalBuildComponent: com.google.devtools.build.v1.StreamId.BuildComponent) =
            when (originalBuildComponent.number) {
                1 -> BuildComponent.Controller
                2 -> BuildComponent.Worker
                3 -> BuildComponent.Tool
                else -> BuildComponent.UnknownComponent
            }

    companion object {
        private val logger = Logger.getLogger(BuildEventConverter::class.java.name)
    }
}